"""initial_schema

Revision ID: 52a27ac918e8
Revises: 
Create Date: 2026-10-05 18:13:12.892141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a27ac918e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('instrument', sa.String(length=100), nullable=True),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('expiry', sa.String(length=50), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('option_type', sa.String(length=20), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('day_high', sa.Float(), nullable=True),
    sa.Column('day_low', sa.Float(), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('open_interest', sa.String(length=50), nullable=True),
    sa.Column('pcr', sa.Float(), nullable=True),
    sa.Column('india_vix', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('primary_scenario', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('market_structure', sa.Text(), nullable=True),
    sa.Column('support_levels', sa.Text(), nullable=True),
    sa.Column('resistance_levels', sa.Text(), nullable=True),
    sa.Column('candlestick_analysis', sa.Text(), nullable=True),
    sa.Column('volume_analysis', sa.Text(), nullable=True),
    sa.Column('oi_analysis', sa.Text(), nullable=True),
    sa.Column('technical_indicators', sa.Text(), nullable=True),
    sa.Column('bullish_scenario', sa.Text(), nullable=True),
    sa.Column('bearish_scenario', sa.Text(), nullable=True),
    sa.Column('sideways_scenario', sa.Text(), nullable=True),
    sa.Column('risk_analysis', sa.Text(), nullable=True),
    sa.Column('trade_setup', sa.Text(), nullable=True),
    sa.Column('time_movements', sa.Text(), nullable=True),
    sa.Column('multi_timeframe_synthesis', sa.Text(), nullable=True),
    sa.Column('detected_overlays', sa.Text(), nullable=True),
    sa.Column('entry_zone', sa.String(length=100), nullable=True),
    sa.Column('stop_loss_zone', sa.String(length=100), nullable=True),
    sa.Column('target_zone', sa.String(length=100), nullable=True),
    sa.Column('confirmation_conditions', sa.Text(), nullable=True),
    sa.Column('invalidating_conditions', sa.Text(), nullable=True),
    sa.Column('time_horizon', sa.String(length=100), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_table('analysis_screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_screenshots_id'), 'analysis_screenshots', ['id'], unique=False)
    op.create_table('scenario_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_direction', sa.String(length=100), nullable=True),
    sa.Column('expected_range', sa.String(length=100), nullable=True),
    sa.Column('timeframe', sa.String(length=100), nullable=True),
    sa.Column('trigger_condition', sa.Text(), nullable=True),
    sa.Column('invalidation_condition', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_predictions_id'), 'scenario_predictions', ['id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('last_analysis_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_scenario_predictions_id'), table_name='scenario_predictions')
    op.drop_table('scenario_predictions')
    op.drop_index(op.f('ix_analysis_screenshots_id'), table_name='analysis_screenshots')
    op.drop_table('analysis_screenshots')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
